### ISSUE TITLE
How to run the test agent?

### ISSUE THREAD

**Issue by Vonisoa** [bdvllrs/marl-patrolling-agents#1]
Hi, I tested the agent under the test folder but I have error saying :

> RuntimeError: size mismatch, m1: [128 x 4], m2: [72 x 512]
Thanks

**Comment by bdvllrs** [comment]
Hi,
Sorry about the late reply.
To test the agent, execute the `main_dqn.py` or the `main_ddpg.py` file.

I should remove the test folder as it does not contain useful code.
